### ISSUE TITLE
Problem using xtb library

### ISSUE THREAD

**Issue by mgoullieux** [sergio-marti/qm3#2]
Dear Sergio, 

I am currently going through the test case provided in samples/oxy-cope. I am having troubles to run the relaxation with the script 02-dynamics-prev.py. 
Indeed, I get the following error message:

>> connectivity: Python residue based search
Traceback (most recent call last):
  File "02-dynamics-prev.py", line 71, in <module>
    obj = my_problem()
  File "02-dynamics-prev.py", line 42, in __init__
    self.eqm = qm3.engines.xtb.dl_xtb( self.mol, 0, 0, sqm, smm )
  File "/home/mgoullieux/tools/qm3/qm3/engines/xtb.py", line 141, in __init__
    ctypes.POINTER( ctypes.c_double ) ]
  File "/home/mgoullieux/miniconda3/lib/python3.7/ctypes/__init__.py", line 377, in __getattr__
    func = self.__getitem__(name)
  File "/home/mgoullieux/miniconda3/lib/python3.7/ctypes/__init__.py", line 382, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: python: undefined symbol: qm3_xtb_calc_

I assume that it comes from the path of xtb, but I don't know how to solve the problem. Specifying the path where xtb has been installed with conda does not help. Would you have any idea how to solve this ?

Thank you for your help!
Regards, 
Mathilde

**Comment by sergio-marti** [comment]
Hi!
Unfortunately, you can not use the in-memory version of xTB (xtb.so) within QM3 from a conda installation. The reason is that QM3 makes use of the fortran headers, which are not provided with the conda distribution.

One option is to install xTB from its source code (https://github.com/grimme-lab/xtb).

The other way relies on the xtb executable.
This option is slower, but will definitively work.
I'm attaching a modified version of the 02-dynamics-prev.py script, which first defines a proper xTB input, and then sets up the eqm engine for an external execution.  

[02-dynamics-prev2.txt](https://github.com/sergio-marti/qm3/files/6747594/02-dynamics-prev2.txt)

**Comment by mgoullieux** [comment]
Dear Sergio,

Thank you very much for the help you provided. The second solution you proposed worked.
However, if possible, I would like to go with the first option, and I already installed xtb from the source code. However, I still get the error, probably because I don't really know how to specify the path of which xtb the script should use.

I tried to add the following line in the python script:
os.environ["QM3_LIBXTB"] = "/home/mgoullieux/tools/xtb/libxtb.so" (this is where I installed xtb from the source code)

but that still provides a similar error as before (AttributeError: /home/mgoullieux/tools/xtb/libxtb.so: undefined symbol: qm3_xtb_calc_)

Would you know if it has to do with the way I installed xtb ?

Best regards, 
Mathilde

**Comment by sergio-marti** [comment]
Hi!

This works for me on an arch linux desktop (with gfortran and cmake)
(I'm assuming that OpenBLAS, xTB and QM3 will be all placed in the home folder...)

git clone https://github.com/xianyi/OpenBLAS.git
cd ~/OpenBLAS
make
export BLAS=$HOME/OpenBLAS/libopenblas.a

git clone https://github.com/grimme-lab/xtb.git
cd ~/xtb
mkdir dist
cd dist
cmake -DCMAKE_BUILD_TYPE=Release -DLAPACK_LIBRARIES=$BLAS -DBLAS_LIBRARIES=$BLAS ..
make

cd ~/qm3
vim config

MTH = OpenBLAS
MLB = HOME_FOLDER/OpenBLAS/libopenblas.a -lpthread

XTB = HOME_FOLDER/xtb/dist

make xtb.so



The point is that the libxtb.so generated during the xTB compilation doesn't work directly with qm3
(/home/mgoullieux/tools/xtb/libxtb.so in your system)

you have to compile the provided file qm3/engines/xtb.f90, and link against the xTB library
this is achieved through "make xtb.so", in the QM3 folder...

then, the QM3_LIBXTB should point to this xtb.so generated file

**Comment by sergio-marti** [comment]
Sorry, i now realize the problem (i believe...)



you must execute in the qm3 folder:

make xtb.so

this will compile a fortran code within qm3, and link against libxtb.so library

**Comment by mgoullieux** [comment]
OK it is clearer now, thanks a lot for your help!
